import type { AnalysisResult, Config, GateStatus } from "../types";
import type { GateResult } from "../gate";

export const COMMENT_MARKER = "<!-- hotspot-tool:pr-comment -->";

const STATUS_BADGE: Record<GateStatus, string> = {
  pass: "✅ **Pass**",
  warn: "⚠️ **Warn**",
  fail: "❌ **Fail**",
};

function pct(n: number): string {
  return `${n.toFixed(0)}%`;
}

/** Build the PR comment body (the hero artifact). */
export function renderPrComment(
  analysis: AnalysisResult,
  gate: GateResult,
  config: Config,
  behavioralOnly: boolean,
): string {
  const lines: string[] = [];
  lines.push(COMMENT_MARKER);
  lines.push("## 🔥 Hotspot report");
  lines.push("");
  lines.push(
    `${STATUS_BADGE[gate.status]} — analyzed ${analysis.totalFilesAnalyzed} files over the last ${analysis.windowDays} days · enforcement: \`${config.enforcementLevel}\``,
  );
  lines.push("");

  if (gate.touchedHotspots.length === 0 && gate.distanceViolations.length === 0) {
    lines.push("No hotspots touched by this PR. Nice — nothing rotting here. 🌱");
  } else {
    lines.push(`### This PR touches ${gate.touchedHotspots.length} hotspot file(s)`);
    lines.push("");
    lines.push("| File | Percentile | Commits | Authors | Bug-fix ratio |");
    lines.push("|---|---|---|---|---|");
    for (const h of gate.touchedHotspots) {
      lines.push(
        `| \`${h.path}\` | ${pct(h.percentile)} | ${h.commitCount} | ${h.authorCount} | ${pct(h.bugfixRatio * 100)} |`,
      );
    }
    lines.push("");
    if (gate.distanceViolations.length > 0) {
      lines.push("**Martin's Distance gate:**");
      for (const v of gate.distanceViolations) {
        lines.push(`- \`${v.path}\` — D ${v.distance.toFixed(2)} exceeds \`distance-max\` ${config.distanceMax}`);
      }
      lines.push("");
    }
    lines.push(
      "> These files are both **messy** and **frequently changed** — the intersection where debt actually costs money. Leave them a little better than you found them.",
    );
  }

  lines.push("");
  lines.push("<details><summary>Top hotspots across the whole repo</summary>");
  lines.push("");
  lines.push("| Rank | File | Percentile | Commits | Authors |");
  lines.push("|---|---|---|---|---|");
  analysis.hotspots.slice(0, 10).forEach((h, i) => {
    lines.push(`| ${i + 1} | \`${h.path}\` | ${pct(h.percentile)} | ${h.commitCount} | ${h.authorCount} |`);
  });
  if (analysis.hotspots.length === 0) lines.push("| — | _none above thresholds_ | | | |");
  lines.push("");
  lines.push("</details>");

  if (behavioralOnly) {
    lines.push("");
    lines.push(
      "_Behavioral-only run: ranking uses change frequency. Complexity & Martin's metrics activate once the static engine is enabled for this repo's languages._",
    );
  }

  lines.push("");
  lines.push("<sub>🔥 Generated by hotspot-tool — mess × activity, measured in your own runner.</sub>");
  return lines.join("\n");
}

/** Build the full job summary (complete breakdown for the Actions run). */
export function renderJobSummary(analysis: AnalysisResult, gate: GateResult, config: Config): string {
  const lines: string[] = [];
  lines.push("# 🔥 Hotspot analysis");
  lines.push("");
  lines.push(`- **Status:** ${gate.status}`);
  lines.push(`- **Files analyzed:** ${analysis.totalFilesAnalyzed}`);
  lines.push(`- **Window:** ${analysis.windowDays} days`);
  lines.push(`- **Hotspots (repo-wide):** ${analysis.hotspots.length}`);
  lines.push(`- **Hotspots touched by PR:** ${gate.touchedHotspots.length}`);
  lines.push("");

  if (analysis.hotspots.length > 0) {
    lines.push("## Repo hotspots");
    lines.push("| Rank | File | Percentile | Commits | Authors | Bug-fix ratio |");
    lines.push("|---|---|---|---|---|---|");
    analysis.hotspots.slice(0, 25).forEach((h, i) => {
      lines.push(
        `| ${i + 1} | \`${h.path}\` | ${pct(h.percentile)} | ${h.commitCount} | ${h.authorCount} | ${pct(h.bugfixRatio * 100)} |`,
      );
    });
    lines.push("");
  }

  if (analysis.coupling.length > 0) {
    lines.push("## Change coupling (files that change together)");
    lines.push("| File A | File B | Shared commits | Degree |");
    lines.push("|---|---|---|---|");
    for (const c of analysis.coupling.slice(0, 15)) {
      lines.push(`| \`${c.a}\` | \`${c.b}\` | ${c.sharedCommits} | ${pct(c.degree * 100)} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
